//
//  CreatedEvents.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class CreatedEvents: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _timestamp: String?
    var _date: String?
    var _description: String?
    var _endTime: String?
    var _location: String?
    var _meetingPlace: String?
    var _name: String?
    var _remainingCapacity: String?
    var _role: String?
    var _startTime: String?
    
    class func dynamoDBTableName() -> String {
        
        return "jogarun-mobilehub-2062646821-CreatedEvents"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_timestamp"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_timestamp" : "Timestamp",
            "_date" : "Date",
            "_description" : "Description",
            "_endTime" : "EndTime",
            "_location" : "Location",
            "_meetingPlace" : "MeetingPlace",
            "_name" : "Name",
            "_remainingCapacity" : "RemainingCapacity",
            "_role" : "Role",
            "_startTime" : "StartTime",
        ]
    }
}
