//
//  SignUp.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class SignUp: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _timestamp: String?
    var _date: String?
    var _description: String?
    var _endTime: String?
    var _location: String?
    var _meetingPlace: String?
    var _name: String?
    var _remainingSpots: String?
    var _role: String?
    var _startTime: String?
    
    class func dynamoDBTableName() -> String {
        
        return "jogarun-mobilehub-2062646821-SignUp"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_timestamp"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_timestamp" : "timestamp",
            "_date" : "date",
            "_description" : "description",
            "_endTime" : "endTime",
            "_location" : "location",
            "_meetingPlace" : "meetingPlace",
            "_name" : "name",
            "_remainingSpots" : "remainingSpots",
            "_role" : "role",
            "_startTime" : "startTime",
        ]
    }
}
